// === 6️⃣ PROYECTOS ===
await prisma.proyectos.createMany({
  data: [
    {
      cliente_id: 'C0001',
      nombre_proyecto: 'Edificio Central ACONSA',
      descripcion: 'Construcción del edificio administrativo principal.',
      ubicacion: 'Managua',
      fecha_inicio: new Date('2023-01-10'),
      fecha_fin: new Date('2023-09-30'),
      presupuesto_total: 850000.00,
      estado: 'Completado',
    },
    {
      cliente_id: 'C0003',
      nombre_proyecto: 'Puente Santa Fe',
      descripcion: 'Diseño y construcción de puente vehicular.',
      ubicacion: 'Rivas',
      fecha_inicio: new Date('2023-02-01'),
      fecha_fin: new Date('2023-12-20'),
      presupuesto_total: 1250000.00,
      estado: 'Activo',
    },
    {
      cliente_id: 'C0005',
      nombre_proyecto: 'Urbanización La Esperanza',
      descripcion: 'Construcción de viviendas de interés social.',
      ubicacion: 'León',
      fecha_inicio: new Date('2023-03-01'),
      fecha_fin: new Date('2024-02-15'),
      presupuesto_total: 980000.00,
      estado: 'Activo',
    },
    {
      cliente_id: 'C0004',
      nombre_proyecto: 'Planta de Tratamiento Masaya',
      descripcion: 'Construcción de planta de aguas residuales.',
      ubicacion: 'Masaya',
      fecha_inicio: new Date('2023-04-10'),
      fecha_fin: new Date('2024-01-30'),
      presupuesto_total: 1150000.00,
      estado: 'Activo',
    },
    {
      cliente_id: 'C0006',
      nombre_proyecto: 'Ampliación Carretera Norte',
      descripcion: 'Obra de ampliación y pavimentación de vía principal.',
      ubicacion: 'Estelí',
      fecha_inicio: new Date('2023-05-01'),
      fecha_fin: new Date('2024-03-15'),
      presupuesto_total: 1600000.00,
      estado: 'Activo',
    },
    {
      cliente_id: 'C0002',
      nombre_proyecto: 'Residencial El Lago',
      descripcion: 'Diseño y construcción de complejo habitacional.',
      ubicacion: 'Granada',
      fecha_inicio: new Date('2023-06-10'),
      fecha_fin: new Date('2024-04-20'),
      presupuesto_total: 920000.00,
      estado: 'Activo',
    },
    {
      cliente_id: 'C0008',
      nombre_proyecto: 'Centro Comercial Ocotal',
      descripcion: 'Construcción de centro comercial de dos niveles.',
      ubicacion: 'Ocotal',
      fecha_inicio: new Date('2023-07-01'),
      fecha_fin: new Date('2024-05-10'),
      presupuesto_total: 1450000.00,
      estado: 'Activo',
    },
    {
      cliente_id: 'C0009',
      nombre_proyecto: 'Parque Industrial Chinandega',
      descripcion: 'Diseño de infraestructura para empresas manufactureras.',
      ubicacion: 'Chinandega',
      fecha_inicio: new Date('2023-08-05'),
      fecha_fin: new Date('2024-06-30'),
      presupuesto_total: 2100000.00,
      estado: 'En Espera',
    },
    {
      cliente_id: 'C0010',
      nombre_proyecto: 'Hospital Bluefields',
      descripcion: 'Construcción de hospital regional con capacidad de 80 camas.',
      ubicacion: 'Bluefields',
      fecha_inicio: new Date('2023-09-15'),
      fecha_fin: new Date('2024-07-10'),
      presupuesto_total: 1850000.00,
      estado: 'Activo',
    },
    {
      cliente_id: 'C0007',
      nombre_proyecto: 'Escuela Técnica Estelí',
      descripcion: 'Rehabilitación de aulas y talleres técnicos.',
      ubicacion: 'Estelí',
      fecha_inicio: new Date('2023-10-01'),
      fecha_fin: new Date('2024-03-20'),
      presupuesto_total: 450000.00,
      estado: 'En Espera',
    },
  ],
  skipDuplicates: true,
});

// === 7️⃣ AVALUOS ===
await prisma.avaluos.createMany({
  data: [
    { proyecto_id: 1, descripcion: 'Evaluación inicial del terreno.', monto_ejecutado: 120000.00, fecha_inicio: new Date('2023-01-10'), fecha_fin: new Date('2023-02-15') },
    { proyecto_id: 2, descripcion: 'Estudio de suelo y fundaciones.', monto_ejecutado: 180000.00, fecha_inicio: new Date('2023-02-05'), fecha_fin: new Date('2023-03-20') },
    { proyecto_id: 3, descripcion: 'Primera fase de urbanización.', monto_ejecutado: 250000.00, fecha_inicio: new Date('2023-03-10'), fecha_fin: new Date('2023-05-05') },
    { proyecto_id: 4, descripcion: 'Obra civil de la planta de tratamiento.', monto_ejecutado: 310000.00, fecha_inicio: new Date('2023-04-15'), fecha_fin: new Date('2023-06-10') },
    { proyecto_id: 5, descripcion: 'Asfaltado y drenaje pluvial.', monto_ejecutado: 400000.00, fecha_inicio: new Date('2023-05-20'), fecha_fin: new Date('2023-07-01') },
    { proyecto_id: 6, descripcion: 'Construcción de muros perimetrales.', monto_ejecutado: 150000.00, fecha_inicio: new Date('2023-06-25'), fecha_fin: new Date('2023-07-30') },
    { proyecto_id: 7, descripcion: 'Estructura metálica del centro comercial.', monto_ejecutado: 520000.00, fecha_inicio: new Date('2023-07-10'), fecha_fin: new Date('2023-09-01') },
    { proyecto_id: 8, descripcion: 'Diseño y movimiento de tierra.', monto_ejecutado: 80000.00, fecha_inicio: new Date('2023-08-10'), fecha_fin: new Date('2023-09-05') },
    { proyecto_id: 9, descripcion: 'Colocación de cimientos hospitalarios.', monto_ejecutado: 600000.00, fecha_inicio: new Date('2023-09-20'), fecha_fin: new Date('2023-11-15') },
    { proyecto_id: 10, descripcion: 'Reparación de techos y aulas.', monto_ejecutado: 90000.00, fecha_inicio: new Date('2023-10-10'), fecha_fin: new Date('2023-11-20') },
  ],
  skipDuplicates: true,
});

// === 8️⃣ SERVICIOS ===
await prisma.servicios.createMany({
  data: [
    { nombre_servicio: 'Excavación de Terreno', descripcion: 'Remoción y nivelación del terreno.', precio_unitario: 150.00, cantidad: 300, fecha_inicio: new Date('2023-01-10'), fecha_fin: new Date('2023-01-20'), unidad_de_medida: 'm³', estado: 'Completado' },
    { nombre_servicio: 'Colocación de Cimientos', descripcion: 'Vertido de concreto estructural.', precio_unitario: 250.00, cantidad: 200, fecha_inicio: new Date('2023-02-05'), fecha_fin: new Date('2023-02-25'), unidad_de_medida: 'm³', estado: 'Completado' },
    { nombre_servicio: 'Levantamiento de Muros', descripcion: 'Bloques de concreto y refuerzo.', precio_unitario: 210.00, cantidad: 500, fecha_inicio: new Date('2023-03-01'), fecha_fin: new Date('2023-04-01'), unidad_de_medida: 'm²', estado: 'Completado' },
    { nombre_servicio: 'Instalación Eléctrica', descripcion: 'Cableado y paneles eléctricos.', precio_unitario: 180.00, cantidad: 400, fecha_inicio: new Date('2023-04-10'), fecha_fin: new Date('2023-05-15'), unidad_de_medida: 'm', estado: 'En progreso' },
    { nombre_servicio: 'Colocación de Tuberías', descripcion: 'Sistemas hidráulicos y sanitarios.', precio_unitario: 90.00, cantidad: 600, fecha_inicio: new Date('2023-05-15'), fecha_fin: new Date('2023-06-10'), unidad_de_medida: 'm', estado: 'Completado' },
    { nombre_servicio: 'Pintura Exterior', descripcion: 'Aplicación de pintura y sellador.', precio_unitario: 75.00, cantidad: 800, fecha_inicio: new Date('2023-06-15'), fecha_fin: new Date('2023-07-01'), unidad_de_medida: 'm²', estado: 'En progreso' },
    { nombre_servicio: 'Montaje de Estructuras', descripcion: 'Colocación de vigas y techos metálicos.', precio_unitario: 320.00, cantidad: 250, fecha_inicio: new Date('2023-07-05'), fecha_fin: new Date('2023-08-15'), unidad_de_medida: 'm²', estado: 'Completado' },
    { nombre_servicio: 'Asfaltado de Calles', descripcion: 'Capa de rodamiento con mezcla caliente.', precio_unitario: 180.00, cantidad: 700, fecha_inicio: new Date('2023-08-20'), fecha_fin: new Date('2023-09-15'), unidad_de_medida: 'm²', estado: 'Completado' },
    { nombre_servicio: 'Instalación de Ventanas', descripcion: 'Ventanas de aluminio y vidrio templado.', precio_unitario: 150.00, cantidad: 120, fecha_inicio: new Date('2023-09-25'), fecha_fin: new Date('2023-10-15'), unidad_de_medida: 'unidad', estado: 'Activo' },
    { nombre_servicio: 'Colocación de Pisos', descripcion: 'Instalación de cerámica y losetas.', precio_unitario: 100.00, cantidad: 500, fecha_inicio: new Date('2023-10-20'), fecha_fin: new Date('2023-11-25'), unidad_de_medida: 'm²', estado: 'Activo' },
  ],
  skipDuplicates: true,
});
