Create database AconsaBD
Use AconsaBD

-- ROLES
CREATE TABLE roles (
  rol_id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cargo               VARCHAR(100),
  descripcion         VARCHAR(150),
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP
);

-- EMPLEADOS
CREATE TABLE empleados (
  empleado_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombres             VARCHAR(100) NOT NULL,
  apellidos           VARCHAR(100) NOT NULL,
  cedula              VARCHAR(25)  NOT NULL,
  rol_id              INT NOT NULL,
  fecha_nacimiento    DATE NOT NULL,
  fecha_contratacion  DATE NOT NULL,
  direccion           VARCHAR(150),
  pais                VARCHAR(50),
  telefono            VARCHAR(15),
  correo              VARCHAR(100) CHECK (correo LIKE '%_@%.%'),
  reportes            INT,
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_empleados_rol    FOREIGN KEY (rol_id)    REFERENCES roles (rol_id),
  CONSTRAINT fk_empleados_jefe   FOREIGN KEY (reportes)  REFERENCES empleados (empleado_id)
);

-- CLIENTES
CREATE TABLE clientes (
  cliente_id          CHAR(5) PRIMARY KEY,
  nombre_empresa      VARCHAR(100) NOT NULL,
  nombre_contacto     VARCHAR(100),
  cargo_contacto      VARCHAR(50),
  direccion           VARCHAR(150),
  ciudad              VARCHAR(100),
  pais                VARCHAR(50),
  telefono            VARCHAR(20),
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP
);

-- CATEGORIAS DE PROVEEDORES
CREATE TABLE categorias_proveedor (
  categoria_proveedor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria       VARCHAR(100) NOT NULL,
  descripcion            VARCHAR(150),
  fecha_creacion         TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion    TIMESTAMP,
  fecha_eliminacion      TIMESTAMP
);

-- PROVEEDORES
CREATE TABLE proveedores (
  proveedor_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_proveedor_id INT NOT NULL,
  nombre_empresa       VARCHAR(100) NOT NULL,
  nombre_contacto      VARCHAR(100),
  cargo_contacto       VARCHAR(50),
  direccion            VARCHAR(150),
  ciudad               VARCHAR(100),
  pais                 VARCHAR(50),
  telefono             VARCHAR(15),
  correo               VARCHAR(100) CHECK (correo LIKE '%_@%.%'),
  fecha_creacion       TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion  TIMESTAMP,
  fecha_eliminacion    TIMESTAMP,
  CONSTRAINT fk_proveedores_categoria FOREIGN KEY (categoria_proveedor_id)
    REFERENCES categorias_proveedor (categoria_proveedor_id)
);

-- PROYECTOS
CREATE TABLE proyectos (
  proyecto_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id          CHAR(5) NOT NULL,
  nombre_proyecto     VARCHAR(100) NOT NULL,
  descripcion         VARCHAR(150),
  ubicacion           VARCHAR(100),
  fecha_inicio        DATE NOT NULL,
  fecha_fin           DATE,
  tiempo_total_dias   INT GENERATED ALWAYS AS ((fecha_fin - fecha_inicio)) STORED,
  presupuesto_total   NUMERIC(18,2) NOT NULL CHECK (presupuesto_total >= 0),
  estado              VARCHAR(50) NOT NULL CHECK (estado IN ('En Espera','Activo','Completado','Cancelado')),
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_proyectos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (cliente_id)
);

-- DETALLES EMPLEADOS
CREATE TABLE detalles_empleados (
  detalle_empleado_id  INT GENERATED BY DEFAULT AS IDENTITY,
  empleado_id          INT NOT NULL,
  proyecto_id          INT NOT NULL,
  fecha_de_proyecto    DATE,
  fecha_creacion       TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion  TIMESTAMP,
  fecha_eliminacion    TIMESTAMP,
  PRIMARY KEY (detalle_empleado_id, empleado_id, proyecto_id),
  CONSTRAINT fk_detalle_empleado FOREIGN KEY (empleado_id) REFERENCES empleados (empleado_id),
  CONSTRAINT fk_detalle_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos (proyecto_id)
);

-- CATEGORIAS
CREATE TABLE categorias (
  categoria_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria    VARCHAR(100) NOT NULL,
  descripcion         VARCHAR(150) NOT NULL,
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP
);

-- PRODUCTOS
CREATE TABLE productos (
  producto_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_producto     VARCHAR(100) NOT NULL,
  categoria_id        INT,
  descripcion         VARCHAR(150),
  unidad_de_medida    VARCHAR(100) NOT NULL,
  cantidad_en_stock   INT NOT NULL,
  precio_unitario     NUMERIC(18,2) NOT NULL CHECK (precio_unitario >= 0),
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (categoria_id)
);

-- AVALUOS
CREATE TABLE avaluos (
  avaluo_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id         INT NOT NULL,
  descripcion         VARCHAR(200),
  monto_ejecutado     NUMERIC(18,2) NOT NULL CHECK (monto_ejecutado >= 0),
  fecha_inicio        TIMESTAMP NOT NULL,
  fecha_fin           TIMESTAMP NOT NULL,
  tiempo_total_dias   INT GENERATED ALWAYS AS ((fecha_fin::date - fecha_inicio::date)) STORED,
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_avaluos_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos (proyecto_id)
);

-- SERVICIOS
CREATE TABLE servicios (
  servicio_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_servicio     VARCHAR(100) NOT NULL,
  descripcion         VARCHAR(200),
  precio_unitario     NUMERIC(18,2) NOT NULL,
  cantidad            INT NOT NULL,
  total               NUMERIC GENERATED ALWAYS AS ((precio_unitario * cantidad)) STORED,
  fecha_inicio        DATE,
  fecha_fin           DATE,
  tiempo_total_dias   INT GENERATED ALWAYS AS ((fecha_fin - fecha_inicio)) STORED,
  unidad_de_medida    VARCHAR(50) NOT NULL,
  estado              VARCHAR(30),
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
);

-- DETALLES SERVICIOS
CREATE TABLE detalles_servicios (
  detalle_servicio_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  servicio_id          INT NOT NULL,
  producto_id          INT NOT NULL,
  descripcion          VARCHAR(200),
  cantidad             INT NOT NULL CHECK (cantidad > 0),
  unidad_de_medida     VARCHAR(50) NOT NULL,
  precio_unitario      NUMERIC(18,2) NOT NULL CHECK (precio_unitario >= 0),
  subtotal             NUMERIC GENERATED ALWAYS AS ((cantidad * precio_unitario)) STORED,
  estado               VARCHAR(30) CHECK (estado IN ('Planificado','Utilizado','Cancelado')),
  fecha_uso            DATE,
  observaciones        VARCHAR(200),
  fecha_creacion       TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion  TIMESTAMP,
  fecha_eliminacion    TIMESTAMP,

  CONSTRAINT fk_detalle_servicio FOREIGN KEY (servicio_id) REFERENCES servicios (servicio_id),
  CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES productos (producto_id)
);

-- MAQUINARIAS
CREATE TABLE maquinarias (
  maquinaria_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_id        INT,
  nombre_maquinaria   VARCHAR(100) NOT NULL,
  marca               VARCHAR(50),
  modelo              VARCHAR(50),
  precio_por_hora     NUMERIC(18,2) NOT NULL CHECK (precio_por_hora >= 0),
  descripcion         VARCHAR(200),
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_maquinarias_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (proveedor_id)
);

-- DETALLES MAQUINARIAS
CREATE TABLE detalles_maquinarias (
  detalle_maquinaria_id INT GENERATED BY DEFAULT AS IDENTITY,
  proyecto_id           INT,
  maquinaria_id         INT,
  horas_utilizadas      INT,
  fecha_inicio_renta    DATE NOT NULL,
  fecha_fin_renta       DATE,
  estado                VARCHAR(30) CHECK (estado IN ('Activa','Finalizada','Cancelada')),
  fecha_creacion        TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion   TIMESTAMP,
  fecha_eliminacion     TIMESTAMP,
  PRIMARY KEY (detalle_maquinaria_id, proyecto_id, maquinaria_id),
  CONSTRAINT fk_detalle_proyecto_maq FOREIGN KEY (proyecto_id)  REFERENCES proyectos (proyecto_id),
  CONSTRAINT fk_detalle_maquinaria FOREIGN KEY (maquinaria_id) REFERENCES maquinarias (maquinaria_id)
);

-- VEHICULOS
CREATE TABLE vehiculos (
  vehiculo_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_id        INT,
  marca               VARCHAR(50) NOT NULL,
  modelo              VARCHAR(50) NOT NULL,
  anio                INT CHECK (anio >= 1886 AND anio <= EXTRACT(YEAR FROM CURRENT_DATE)),
  placa               VARCHAR(15) UNIQUE NOT NULL,
  tipo_de_vehiculo    VARCHAR(30),
  tipo_de_combustible VARCHAR(40),
  estado              VARCHAR(20) CHECK (estado IN ('Disponible','En Mantenimiento','No Disponible')),
  fecha_registro      DATE,
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_vehiculos_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (proveedor_id)
);

-- DETALLES VEHICULOS
CREATE TABLE detalles_vehiculos (
  detalle_vehiculo_id  INT GENERATED BY DEFAULT AS IDENTITY,
  empleado_id          INT NOT NULL,
  vehiculo_id          INT NOT NULL,
  fecha_asignacion     DATE NOT NULL,
  fecha_fin_asignacion DATE,
  descripcion          VARCHAR(100),
  fecha_creacion       TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion  TIMESTAMP,
  fecha_eliminacion    TIMESTAMP,
  PRIMARY KEY (detalle_vehiculo_id, empleado_id, vehiculo_id),
  CONSTRAINT fk_detalle_empleado_veh FOREIGN KEY (empleado_id) REFERENCES empleados (empleado_id),
  CONSTRAINT fk_detalle_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES vehiculos (vehiculo_id)
);

-- USUARIOS
CREATE TABLE usuarios (
  usuario_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empleado_id         INT NOT NULL,
  usuario             VARCHAR(100) NOT NULL,
  contrasena          VARCHAR(200) NOT NULL,
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_usuarios_empleado FOREIGN KEY (empleado_id) REFERENCES empleados (empleado_id)
);

-- COMPRAS
CREATE TABLE compras (
  compra_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_id        INT NOT NULL,
  empleado_id         INT,
  numero_factura      VARCHAR(50) NOT NULL,
  fecha_compra        DATE NOT NULL DEFAULT CURRENT_DATE,
  monto_total         NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (monto_total >= 0),
  estado              VARCHAR(50) NOT NULL CHECK (estado IN ('Pendiente','Pagada','Cancelada')),
  observaciones       VARCHAR(200),
  fecha_creacion      TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP,
  fecha_eliminacion   TIMESTAMP,
  CONSTRAINT fk_compras_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (proveedor_id),
  CONSTRAINT fk_compras_empleado  FOREIGN KEY (empleado_id)  REFERENCES empleados (empleado_id)
);

-- DETALLES COMPRAS
CREATE TABLE detalles_compras (
  detalle_compra_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id            INT NOT NULL,
  producto_id          INT NOT NULL,
  cantidad             INT NOT NULL CHECK (cantidad > 0),
  precio_unitario      NUMERIC(18,2) NOT NULL CHECK (precio_unitario >= 0),
  subtotal             NUMERIC GENERATED ALWAYS AS ((cantidad * precio_unitario)) STORED,
  fecha_creacion       TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion  TIMESTAMP,
  fecha_eliminacion    TIMESTAMP,
  CONSTRAINT fk_detalle_compra FOREIGN KEY (compra_id) REFERENCES compras (compra_id),
  CONSTRAINT fk_detalle_producto_comp FOREIGN KEY (producto_id) REFERENCES productos (producto_id)
);

-- AVALUOS_SERVICIOS (tabla puente M:N)
CREATE TABLE avaluos_servicios (
  avaluo_servicio_id   INT GENERATED BY DEFAULT AS IDENTITY,
  avaluo_id            INT NOT NULL,
  servicio_id          INT NOT NULL,

  cantidad             INT NOT NULL CHECK (cantidad > 0),
  precio_unitario      NUMERIC(18,2) NOT NULL CHECK (precio_unitario >= 0),
  total                NUMERIC GENERATED ALWAYS AS ((cantidad * precio_unitario)) STORED,

  observaciones        VARCHAR(200),
  fecha_creacion       TIMESTAMP DEFAULT NOW(),
  fecha_actualizacion  TIMESTAMP,
  fecha_eliminacion    TIMESTAMP,

  PRIMARY KEY (avaluo_servicio_id, avaluo_id, servicio_id),
  CONSTRAINT fk_as_avaluo   FOREIGN KEY (avaluo_id)   REFERENCES avaluos (avaluo_id),
  CONSTRAINT fk_as_servicio FOREIGN KEY (servicio_id) REFERENCES servicios (servicio_id),
);
