-- ============================================================
-- SCRIPT COMPLETO BASE DE DATOS ACONSA
-- PostgreSQL
-- Usuario propietario: roger
-- Incluye: tablas, índices, funciones, triggers, ALTER y GRANT
-- ============================================================

-- ============================================================
-- 1. LIMPIEZA DE TABLAS
-- ============================================================

DROP TABLE IF EXISTS public.reportes_generados CASCADE;
DROP TABLE IF EXISTS public.permisos CASCADE;
DROP TABLE IF EXISTS public.menu CASCADE;
DROP TABLE IF EXISTS public.detalles_avaluos CASCADE;
DROP TABLE IF EXISTS public.detalles_compras CASCADE;
DROP TABLE IF EXISTS public.movimientos_inventario CASCADE;
DROP TABLE IF EXISTS public.alertas_inventario CASCADE;
DROP TABLE IF EXISTS public.compras CASCADE;
DROP TABLE IF EXISTS public.historial_alertas CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;
DROP TABLE IF EXISTS public.detalles_vehiculos CASCADE;
DROP TABLE IF EXISTS public.vehiculos CASCADE;
DROP TABLE IF EXISTS public.detalles_maquinarias CASCADE;
DROP TABLE IF EXISTS public.maquinarias CASCADE;
DROP TABLE IF EXISTS public.costos_indirectos_servicios CASCADE;
DROP TABLE IF EXISTS public.costos_directos_servicios CASCADE;
DROP TABLE IF EXISTS public.servicios CASCADE;
DROP TABLE IF EXISTS public.avaluos CASCADE;
DROP TABLE IF EXISTS public.materiales CASCADE;
DROP TABLE IF EXISTS public.categorias CASCADE;
DROP TABLE IF EXISTS public.detalles_empleados CASCADE;
DROP TABLE IF EXISTS public.proyectos CASCADE;
DROP TABLE IF EXISTS public.proveedores CASCADE;
DROP TABLE IF EXISTS public.categorias_proveedor CASCADE;
DROP TABLE IF EXISTS public.clientes CASCADE;
DROP TABLE IF EXISTS public.empleados CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;

-- ============================================================
-- 2. TABLAS BASE
-- ============================================================

CREATE TABLE public.roles (
    rol_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo               VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(150),
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ
);

CREATE TABLE public.empleados (
    empleado_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres             VARCHAR(100) NOT NULL,
    apellidos           VARCHAR(100) NOT NULL,
    cedula              VARCHAR(25) NOT NULL,
    rol_id              INTEGER NOT NULL,
    fecha_nacimiento    DATE NOT NULL,
    fecha_contratacion  DATE NOT NULL,
    direccion           VARCHAR(150),
    pais                VARCHAR(50),
    telefono            VARCHAR(20),
    correo              VARCHAR(100),
    reportes            INTEGER,
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_empleados_roles
        FOREIGN KEY (rol_id)
        REFERENCES public.roles (rol_id),

    CONSTRAINT fk_empleados_jefe
        FOREIGN KEY (reportes)
        REFERENCES public.empleados (empleado_id),

    CONSTRAINT uq_empleados_cedula
        UNIQUE (cedula),

    CONSTRAINT chk_empleados_correo
        CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

CREATE TABLE public.clientes (
    cliente_id            CHAR(5) PRIMARY KEY,
    tipo_cliente          VARCHAR(30) NOT NULL,
    numero_identificacion VARCHAR(50),
    nombre_empresa        VARCHAR(100) NOT NULL,
    nombre_contacto       VARCHAR(100),
    cargo_contacto        VARCHAR(50),
    direccion             VARCHAR(150),
    ciudad                VARCHAR(100),
    pais                  VARCHAR(50),
    telefono              VARCHAR(20),
    correo                VARCHAR(100),
    fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion   TIMESTAMPTZ,
    fecha_eliminacion     TIMESTAMPTZ,

    CONSTRAINT chk_clientes_tipo_cliente
        CHECK (tipo_cliente IN ('Persona Natural', 'Persona Jurídica')),

    CONSTRAINT chk_clientes_correo
        CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

CREATE TABLE public.categorias_proveedor (
    categoria_proveedor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria       VARCHAR(100) NOT NULL,
    descripcion            VARCHAR(150),
    fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion    TIMESTAMPTZ,
    fecha_eliminacion      TIMESTAMPTZ
);

CREATE TABLE public.proveedores (
    proveedor_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_proveedor_id INTEGER NOT NULL,
    nombre_empresa         VARCHAR(100) NOT NULL,
    nombre_contacto        VARCHAR(100),
    cargo_contacto         VARCHAR(50),
    direccion              VARCHAR(150),
    ciudad                 VARCHAR(100),
    pais                   VARCHAR(50),
    telefono               VARCHAR(20),
    correo                 VARCHAR(100),
    fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion    TIMESTAMPTZ,
    fecha_eliminacion      TIMESTAMPTZ,

    CONSTRAINT fk_proveedores_categoria
        FOREIGN KEY (categoria_proveedor_id)
        REFERENCES public.categorias_proveedor (categoria_proveedor_id),

    CONSTRAINT chk_proveedores_correo
        CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

CREATE TABLE public.categorias (
    categoria_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria    VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(150) NOT NULL,
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ
);

-- ============================================================
-- 3. PROYECTOS Y RELACIÓN CON EMPLEADOS
-- ============================================================

CREATE TABLE public.proyectos (
    proyecto_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id          CHAR(5) NOT NULL,
    nombre_proyecto     VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(150),
    ubicacion           VARCHAR(100),
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE,

    tiempo_total_dias   INTEGER GENERATED ALWAYS AS (
        fecha_fin - fecha_inicio
    ) STORED,

    presupuesto_total   NUMERIC(18,2) NOT NULL,
    estado              VARCHAR(50) NOT NULL DEFAULT 'En Espera',
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_proyectos_clientes
        FOREIGN KEY (cliente_id)
        REFERENCES public.clientes (cliente_id),

    CONSTRAINT chk_proyectos_presupuesto
        CHECK (presupuesto_total > 0),

    CONSTRAINT chk_proyectos_estado
        CHECK (estado IN ('En Espera', 'Activo', 'Completado', 'Cancelado')),

    CONSTRAINT chk_proyectos_fechas
        CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE public.detalles_empleados (
    detalle_empleado_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id         INTEGER NOT NULL,
    proyecto_id         INTEGER NOT NULL,
    fecha_de_proyecto   DATE DEFAULT CURRENT_DATE,
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_detalles_empleados_empleados
        FOREIGN KEY (empleado_id)
        REFERENCES public.empleados (empleado_id),

    CONSTRAINT fk_detalles_empleados_proyectos
        FOREIGN KEY (proyecto_id)
        REFERENCES public.proyectos (proyecto_id),

    CONSTRAINT uq_detalles_empleados_empleado_proyecto
        UNIQUE (empleado_id, proyecto_id)
);

-- ============================================================
-- 4. INVENTARIO
-- ============================================================

CREATE TABLE public.materiales (
    material_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_material     VARCHAR(100) NOT NULL,
    categoria_id        INTEGER,
    descripcion         VARCHAR(150),
    unidad_de_medida    VARCHAR(100) NOT NULL,
    cantidad_en_stock   INTEGER NOT NULL,
    stock_minimo        INTEGER NOT NULL DEFAULT 10,
    precio_unitario     NUMERIC(18,2) NOT NULL,
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_materiales_categorias
        FOREIGN KEY (categoria_id)
        REFERENCES public.categorias (categoria_id),

    CONSTRAINT chk_materiales_stock
        CHECK (cantidad_en_stock >= stock_minimo),

    CONSTRAINT chk_materiales_stock_minimo
        CHECK (stock_minimo >= 10),

    CONSTRAINT chk_materiales_precio
        CHECK (precio_unitario > 0)
);

CREATE TABLE public.alertas_inventario (
    alerta_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id         INTEGER NOT NULL,
    tipo_alerta         VARCHAR(50) NOT NULL,
    mensaje             VARCHAR(250) NOT NULL,
    stock_actual        INTEGER NOT NULL,
    stock_minimo        INTEGER NOT NULL DEFAULT 10,
    estado              VARCHAR(30) DEFAULT 'Pendiente',
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_atendida      TIMESTAMPTZ,
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_alertas_materiales
        FOREIGN KEY (material_id)
        REFERENCES public.materiales (material_id),

    CONSTRAINT chk_alertas_tipo
        CHECK (tipo_alerta IN ('Stock Bajo', 'Inventario Crítico')),

    CONSTRAINT chk_alertas_estado
        CHECK (estado IN ('Pendiente', 'Atendida', 'Cancelada'))
);

-- ============================================================
-- 5. AVALÚOS Y SERVICIOS
-- Se usa TIMESTAMP en avalúos para evitar error de generación no inmutable.
-- ============================================================

CREATE TABLE public.avaluos (
    avaluo_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id         INTEGER NOT NULL,
    descripcion         VARCHAR(200),
    monto_ejecutado     NUMERIC(18,2) NOT NULL,
    fecha_inicio        TIMESTAMP NOT NULL,
    fecha_fin           TIMESTAMP NOT NULL,

    tiempo_total_dias   INTEGER GENERATED ALWAYS AS (
        fecha_fin::DATE - fecha_inicio::DATE
    ) STORED,

    fecha_creacion      TIMESTAMP DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP,
    fecha_eliminacion   TIMESTAMP,

    CONSTRAINT fk_avaluos_proyectos
        FOREIGN KEY (proyecto_id)
        REFERENCES public.proyectos (proyecto_id),

    CONSTRAINT chk_avaluos_monto
        CHECK (monto_ejecutado >= 0),

    CONSTRAINT chk_avaluos_fechas
        CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE public.servicios (
    servicio_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_servicio       VARCHAR(100) NOT NULL,
    descripcion           VARCHAR(200),
    total_costo_directo   NUMERIC(18,2) NOT NULL,
    total_costo_indirecto NUMERIC(18,2) NOT NULL,

    costo_venta           NUMERIC(18,2) GENERATED ALWAYS AS (
        total_costo_directo + total_costo_indirecto
    ) STORED,

    fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion   TIMESTAMPTZ,
    fecha_eliminacion     TIMESTAMPTZ,

    CONSTRAINT chk_servicios_total_costo_directo
        CHECK (total_costo_directo > 0),

    CONSTRAINT chk_servicios_total_costo_indirecto
        CHECK (total_costo_indirecto > 0)
);

CREATE TABLE public.costos_directos_servicios (
    costo_directo_id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servicio_id                     INTEGER NOT NULL,
    material_id                     INTEGER NOT NULL,
    cantidad_material               INTEGER NOT NULL,
    unidad_de_medida                VARCHAR(50) NOT NULL,
    precio_unitario                 NUMERIC(18,2) NOT NULL,

    costo_material                  NUMERIC(18,2) GENERATED ALWAYS AS (
        precio_unitario * cantidad_material
    ) STORED,

    mano_obra                       NUMERIC(18,2) GENERATED ALWAYS AS (
        (precio_unitario * cantidad_material) * 0.40
    ) STORED,

    equipos_transporte_herramientas NUMERIC(18,2) GENERATED ALWAYS AS (
        (precio_unitario * cantidad_material) * 0.10
    ) STORED,

    total_costo_directo             NUMERIC(18,2) GENERATED ALWAYS AS (
        (precio_unitario * cantidad_material) +
        ((precio_unitario * cantidad_material) * 0.40) +
        ((precio_unitario * cantidad_material) * 0.10)
    ) STORED,

    fecha_creacion                  TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion             TIMESTAMPTZ,
    fecha_eliminacion               TIMESTAMPTZ,

    CONSTRAINT fk_costos_directos_servicios
        FOREIGN KEY (servicio_id)
        REFERENCES public.servicios (servicio_id),

    CONSTRAINT fk_costos_directos_materiales
        FOREIGN KEY (material_id)
        REFERENCES public.materiales (material_id),

    CONSTRAINT chk_costos_directos_cantidad
        CHECK (cantidad_material > 0),

    CONSTRAINT chk_costos_directos_precio
        CHECK (precio_unitario > 0)
);

CREATE TABLE public.costos_indirectos_servicios (
    costo_indirecto_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servicio_id           INTEGER NOT NULL,
    costo_directo_id      INTEGER NOT NULL,
    total_costo_directo   NUMERIC(18,2) NOT NULL,

    administracion        NUMERIC(18,2) GENERATED ALWAYS AS (
        total_costo_directo * 0.05
    ) STORED,

    operacion             NUMERIC(18,2) GENERATED ALWAYS AS (
        total_costo_directo * 0.10
    ) STORED,

    utilidad              NUMERIC(18,2) GENERATED ALWAYS AS (
        total_costo_directo * 0.15
    ) STORED,

    precio_unitario       NUMERIC(18,2) GENERATED ALWAYS AS (
        (total_costo_directo * 0.05) +
        (total_costo_directo * 0.10) +
        (total_costo_directo * 0.15)
    ) STORED,

    total_costo_indirecto NUMERIC(18,2) GENERATED ALWAYS AS (
        (total_costo_directo * 0.05) +
        (total_costo_directo * 0.10) +
        (total_costo_directo * 0.15)
    ) STORED,

    fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion   TIMESTAMPTZ,
    fecha_eliminacion     TIMESTAMPTZ,

    CONSTRAINT fk_costos_indirectos_servicios
        FOREIGN KEY (servicio_id)
        REFERENCES public.servicios (servicio_id),

    CONSTRAINT fk_costos_indirectos_directos
        FOREIGN KEY (costo_directo_id)
        REFERENCES public.costos_directos_servicios (costo_directo_id),

    CONSTRAINT chk_costos_indirectos_total_directo
        CHECK (total_costo_directo > 0)
);

CREATE TABLE public.detalles_avaluos (
    detalle_avaluo_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaluo_id           INTEGER NOT NULL,
    servicio_id         INTEGER NOT NULL,
    actividad           VARCHAR(100) NOT NULL,
    unidad_de_medida    VARCHAR(50) NOT NULL,
    cantidad            INTEGER NOT NULL,
    precio_unitario     NUMERIC(18,2) NOT NULL,

    costo_venta         NUMERIC(18,2) GENERATED ALWAYS AS (
        cantidad * precio_unitario
    ) STORED,

    iva                 NUMERIC(18,2) GENERATED ALWAYS AS (
        (cantidad * precio_unitario) * 0.15
    ) STORED,

    total_costo_venta   NUMERIC(18,2) GENERATED ALWAYS AS (
        (cantidad * precio_unitario) +
        ((cantidad * precio_unitario) * 0.15)
    ) STORED,

    observaciones       VARCHAR(200),
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_detalles_avaluos_avaluos
        FOREIGN KEY (avaluo_id)
        REFERENCES public.avaluos (avaluo_id),

    CONSTRAINT fk_detalles_avaluos_servicios
        FOREIGN KEY (servicio_id)
        REFERENCES public.servicios (servicio_id),

    CONSTRAINT chk_detalles_avaluos_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_detalles_avaluos_precio
        CHECK (precio_unitario >= 0)
);

-- ============================================================
-- 6. MAQUINARIAS Y VEHÍCULOS
-- ============================================================

CREATE TABLE public.maquinarias (
    maquinaria_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id        INTEGER,
    nombre_maquinaria   VARCHAR(100) NOT NULL,
    marca               VARCHAR(50),
    modelo              VARCHAR(50),
    precio_por_hora     NUMERIC(18,2) NOT NULL,
    descripcion         VARCHAR(200),
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_maquinarias_proveedores
        FOREIGN KEY (proveedor_id)
        REFERENCES public.proveedores (proveedor_id),

    CONSTRAINT chk_maquinarias_precio
        CHECK (precio_por_hora >= 0)
);

CREATE TABLE public.detalles_maquinarias (
    detalle_maquinaria_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id           INTEGER,
    maquinaria_id         INTEGER,
    horas_utilizadas      INTEGER,
    fecha_inicio_renta    DATE NOT NULL,
    fecha_fin_renta       DATE,
    estado                VARCHAR(30),
    fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion   TIMESTAMPTZ,
    fecha_eliminacion     TIMESTAMPTZ,

    CONSTRAINT fk_detalles_maquinarias_proyectos
        FOREIGN KEY (proyecto_id)
        REFERENCES public.proyectos (proyecto_id),

    CONSTRAINT fk_detalles_maquinarias_maquinarias
        FOREIGN KEY (maquinaria_id)
        REFERENCES public.maquinarias (maquinaria_id),

    CONSTRAINT chk_detalles_maquinarias_estado
        CHECK (estado IS NULL OR estado IN ('Activa', 'Finalizada', 'Cancelada')),

    CONSTRAINT chk_detalles_maquinarias_horas
        CHECK (horas_utilizadas IS NULL OR horas_utilizadas >= 0),

    CONSTRAINT chk_detalles_maquinarias_fechas
        CHECK (fecha_fin_renta IS NULL OR fecha_fin_renta >= fecha_inicio_renta)
);

CREATE TABLE public.vehiculos (
    vehiculo_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id         INTEGER,
    marca                VARCHAR(50) NOT NULL,
    modelo               VARCHAR(50) NOT NULL,
    anio                 INTEGER,
    placa                VARCHAR(15) NOT NULL UNIQUE,
    tipo_de_vehiculo     VARCHAR(30),
    tipo_de_combustible  VARCHAR(40),
    estado               VARCHAR(20),
    fecha_registro       DATE,
    fecha_creacion       TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ,
    fecha_eliminacion    TIMESTAMPTZ,

    CONSTRAINT fk_vehiculos_proveedores
        FOREIGN KEY (proveedor_id)
        REFERENCES public.proveedores (proveedor_id),

    CONSTRAINT chk_vehiculos_anio
        CHECK (anio IS NULL OR anio >= 1886),

    CONSTRAINT chk_vehiculos_estado
        CHECK (estado IS NULL OR estado IN ('Disponible', 'En Mantenimiento', 'No Disponible')),

    CONSTRAINT chk_vehiculos_combustible
        CHECK (
            tipo_de_combustible IS NULL
            OR tipo_de_combustible IN ('Diésel', 'Regular', 'Gasolina Super')
        )
);

CREATE TABLE public.detalles_vehiculos (
    detalle_vehiculo_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id          INTEGER NOT NULL,
    vehiculo_id          INTEGER NOT NULL,
    fecha_asignacion     DATE NOT NULL,
    fecha_fin_asignacion DATE,
    descripcion          VARCHAR(100),
    fecha_creacion       TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ,
    fecha_eliminacion    TIMESTAMPTZ,

    CONSTRAINT fk_detalles_vehiculos_empleados
        FOREIGN KEY (empleado_id)
        REFERENCES public.empleados (empleado_id),

    CONSTRAINT fk_detalles_vehiculos_vehiculos
        FOREIGN KEY (vehiculo_id)
        REFERENCES public.vehiculos (vehiculo_id),

    CONSTRAINT chk_detalles_vehiculos_fechas
        CHECK (fecha_fin_asignacion IS NULL OR fecha_fin_asignacion >= fecha_asignacion)
);

-- ============================================================
-- 7. USUARIOS, HISTORIAL, MENÚ Y PERMISOS
-- ============================================================

CREATE TABLE public.usuarios (
    usuario_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id         INTEGER NOT NULL,
    usuario             VARCHAR(100) NOT NULL,
    contrasena          VARCHAR(200) NOT NULL,
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_usuarios_empleados
        FOREIGN KEY (empleado_id)
        REFERENCES public.empleados (empleado_id),

    CONSTRAINT uq_usuarios_usuario
        UNIQUE (usuario)
);

CREATE TABLE public.historial_alertas (
    alerta_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          INTEGER,
    tipo                VARCHAR(60) NOT NULL,
    titulo              VARCHAR(150) NOT NULL,
    mensaje             VARCHAR(300) NOT NULL,
    modulo              VARCHAR(100) NOT NULL,
    referencia_id       INTEGER,
    prioridad           VARCHAR(30) NOT NULL DEFAULT 'Media',
    leida               BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_historial_alertas_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios (usuario_id),

    CONSTRAINT chk_historial_alertas_prioridad
        CHECK (prioridad IN ('Baja', 'Media', 'Alta'))
);

CREATE TABLE public.menu (
    id_menu        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(100) NOT NULL,
    es_submenu     BOOLEAN DEFAULT FALSE,
    url            VARCHAR(150),
    id_menu_parent INTEGER,
    estado         BOOLEAN DEFAULT TRUE,
    show           BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_menu_parent
        FOREIGN KEY (id_menu_parent)
        REFERENCES public.menu (id_menu)
        ON DELETE SET NULL
);

CREATE TABLE public.permisos (
    permiso_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          INTEGER NOT NULL,
    id_menu             INTEGER NOT NULL,
    estado              BOOLEAN DEFAULT TRUE,
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_permisos_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios (usuario_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_permisos_menu
        FOREIGN KEY (id_menu)
        REFERENCES public.menu (id_menu)
        ON DELETE CASCADE,

    CONSTRAINT uq_permisos_usuario_menu
        UNIQUE (usuario_id, id_menu)
);

-- ============================================================
-- 8. COMPRAS Y MOVIMIENTOS DE INVENTARIO
-- ============================================================

CREATE TABLE public.compras (
    compra_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id        INTEGER NOT NULL,
    empleado_id         INTEGER,
    numero_factura      VARCHAR(50) NOT NULL,
    fecha_compra        DATE NOT NULL DEFAULT CURRENT_DATE,
    monto_total         NUMERIC(18,2) NOT NULL DEFAULT 0,
    estado              VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
    observaciones       VARCHAR(200),
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_compras_proveedores
        FOREIGN KEY (proveedor_id)
        REFERENCES public.proveedores (proveedor_id),

    CONSTRAINT fk_compras_empleados
        FOREIGN KEY (empleado_id)
        REFERENCES public.empleados (empleado_id),

    CONSTRAINT uq_compras_numero_factura
        UNIQUE (numero_factura),

    CONSTRAINT chk_compras_monto
        CHECK (monto_total >= 0),

    CONSTRAINT chk_compras_estado
        CHECK (estado IN ('Pendiente', 'Pagada', 'Cancelada'))
);

CREATE TABLE public.detalles_compras (
    detalle_compra_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id           INTEGER NOT NULL,
    material_id         INTEGER NOT NULL,
    cantidad            INTEGER NOT NULL,
    precio_unitario     NUMERIC(18,2) NOT NULL,

    subtotal            NUMERIC(18,2) GENERATED ALWAYS AS (
        cantidad * precio_unitario
    ) STORED,

    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_detalles_compras_compras
        FOREIGN KEY (compra_id)
        REFERENCES public.compras (compra_id),

    CONSTRAINT fk_detalles_compras_materiales
        FOREIGN KEY (material_id)
        REFERENCES public.materiales (material_id),

    CONSTRAINT chk_detalles_compras_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_detalles_compras_precio
        CHECK (precio_unitario > 0)
);

CREATE TABLE public.movimientos_inventario (
    movimiento_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id          INTEGER NOT NULL,
    tipo_movimiento      VARCHAR(30) NOT NULL,
    cantidad             INTEGER NOT NULL,
    stock_anterior       INTEGER NOT NULL,
    stock_nuevo          INTEGER NOT NULL,
    precio_unitario      NUMERIC(18,2),

    costo_total          NUMERIC(18,2) GENERATED ALWAYS AS (
        cantidad * precio_unitario
    ) STORED,

    referencia           VARCHAR(100),
    descripcion          VARCHAR(250),
    usuario_id           INTEGER,
    fecha_movimiento     TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ,
    fecha_eliminacion    TIMESTAMPTZ,

    CONSTRAINT fk_movimientos_materiales
        FOREIGN KEY (material_id)
        REFERENCES public.materiales (material_id),

    CONSTRAINT fk_movimientos_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios (usuario_id),

    CONSTRAINT chk_movimientos_tipo
        CHECK (tipo_movimiento IN ('Entrada', 'Salida', 'Ajuste')),

    CONSTRAINT chk_movimientos_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_movimientos_stock_nuevo
        CHECK (stock_nuevo >= 0)
);

-- ============================================================
-- 9. REPORTES
-- ============================================================

CREATE TABLE public.reportes_generados (
    reporte_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          INTEGER NOT NULL,
    nombre_reporte      VARCHAR(150) NOT NULL,
    tipo_reporte        VARCHAR(20) NOT NULL,
    descripcion         VARCHAR(200),
    datos               JSONB,
    archivo_url         VARCHAR(255) NOT NULL,
    ip_generacion       VARCHAR(50),
    fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    fecha_eliminacion   TIMESTAMPTZ,

    CONSTRAINT fk_reportes_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios (usuario_id),

    CONSTRAINT chk_reportes_tipo
        CHECK (tipo_reporte IN ('PDF', 'EXCEL'))
);

-- ============================================================
-- 10. ÍNDICES
-- ============================================================

CREATE INDEX idx_empleados_rol_id ON public.empleados (rol_id);
CREATE INDEX idx_empleados_reportes ON public.empleados (reportes);
CREATE INDEX idx_proveedores_categoria_id ON public.proveedores (categoria_proveedor_id);
CREATE INDEX idx_proyectos_cliente_id ON public.proyectos (cliente_id);
CREATE INDEX idx_detalles_empleados_empleado_id ON public.detalles_empleados (empleado_id);
CREATE INDEX idx_detalles_empleados_proyecto_id ON public.detalles_empleados (proyecto_id);
CREATE INDEX idx_materiales_categoria_id ON public.materiales (categoria_id);
CREATE INDEX idx_alertas_inventario_material_id ON public.alertas_inventario (material_id);
CREATE INDEX idx_alertas_inventario_estado ON public.alertas_inventario (estado);
CREATE INDEX idx_avaluos_proyecto_id ON public.avaluos (proyecto_id);
CREATE INDEX idx_costos_directos_servicio_id ON public.costos_directos_servicios (servicio_id);
CREATE INDEX idx_costos_directos_material_id ON public.costos_directos_servicios (material_id);
CREATE INDEX idx_costos_indirectos_servicio_id ON public.costos_indirectos_servicios (servicio_id);
CREATE INDEX idx_costos_indirectos_costo_directo_id ON public.costos_indirectos_servicios (costo_directo_id);
CREATE INDEX idx_maquinarias_proveedor_id ON public.maquinarias (proveedor_id);
CREATE INDEX idx_detalles_maquinarias_proyecto_id ON public.detalles_maquinarias (proyecto_id);
CREATE INDEX idx_detalles_maquinarias_maquinaria_id ON public.detalles_maquinarias (maquinaria_id);
CREATE INDEX idx_vehiculos_proveedor_id ON public.vehiculos (proveedor_id);
CREATE INDEX idx_detalles_vehiculos_empleado_id ON public.detalles_vehiculos (empleado_id);
CREATE INDEX idx_detalles_vehiculos_vehiculo_id ON public.detalles_vehiculos (vehiculo_id);
CREATE INDEX idx_usuarios_empleado_id ON public.usuarios (empleado_id);
CREATE INDEX idx_historial_alertas_usuario_id ON public.historial_alertas (usuario_id);
CREATE INDEX idx_historial_alertas_modulo ON public.historial_alertas (modulo);
CREATE INDEX idx_historial_alertas_leida ON public.historial_alertas (leida);
CREATE INDEX idx_compras_proveedor_id ON public.compras (proveedor_id);
CREATE INDEX idx_compras_empleado_id ON public.compras (empleado_id);
CREATE INDEX idx_detalles_compras_compra_id ON public.detalles_compras (compra_id);
CREATE INDEX idx_detalles_compras_material_id ON public.detalles_compras (material_id);
CREATE INDEX idx_detalles_avaluos_avaluo_id ON public.detalles_avaluos (avaluo_id);
CREATE INDEX idx_detalles_avaluos_servicio_id ON public.detalles_avaluos (servicio_id);
CREATE INDEX idx_permisos_usuario_id ON public.permisos (usuario_id);
CREATE INDEX idx_permisos_menu_id ON public.permisos (id_menu);
CREATE INDEX idx_movimientos_inventario_material_id ON public.movimientos_inventario (material_id);
CREATE INDEX idx_movimientos_inventario_usuario_id ON public.movimientos_inventario (usuario_id);
CREATE INDEX idx_movimientos_inventario_fecha ON public.movimientos_inventario (fecha_movimiento);
CREATE INDEX idx_reportes_usuario_id ON public.reportes_generados (usuario_id);

-- ============================================================
-- 11. FUNCIÓN PARA ACTUALIZAR FECHA_ACTUALIZACION
-- ============================================================

CREATE OR REPLACE FUNCTION public.actualizar_fecha_modificacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 12. TRIGGERS PARA FECHA_ACTUALIZACION
-- ============================================================

CREATE TRIGGER trg_roles_update BEFORE UPDATE ON public.roles FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_empleados_update BEFORE UPDATE ON public.empleados FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_clientes_update BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_categorias_proveedor_update BEFORE UPDATE ON public.categorias_proveedor FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_proveedores_update BEFORE UPDATE ON public.proveedores FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_categorias_update BEFORE UPDATE ON public.categorias FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_proyectos_update BEFORE UPDATE ON public.proyectos FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_detalles_empleados_update BEFORE UPDATE ON public.detalles_empleados FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_materiales_update BEFORE UPDATE ON public.materiales FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_alertas_inventario_update BEFORE UPDATE ON public.alertas_inventario FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_avaluos_update BEFORE UPDATE ON public.avaluos FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_servicios_update BEFORE UPDATE ON public.servicios FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_costos_directos_update BEFORE UPDATE ON public.costos_directos_servicios FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_costos_indirectos_update BEFORE UPDATE ON public.costos_indirectos_servicios FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_detalles_avaluos_update BEFORE UPDATE ON public.detalles_avaluos FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_maquinarias_update BEFORE UPDATE ON public.maquinarias FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_detalles_maquinarias_update BEFORE UPDATE ON public.detalles_maquinarias FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_vehiculos_update BEFORE UPDATE ON public.vehiculos FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_detalles_vehiculos_update BEFORE UPDATE ON public.detalles_vehiculos FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_usuarios_update BEFORE UPDATE ON public.usuarios FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_historial_alertas_update BEFORE UPDATE ON public.historial_alertas FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_permisos_update BEFORE UPDATE ON public.permisos FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_compras_update BEFORE UPDATE ON public.compras FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_detalles_compras_update BEFORE UPDATE ON public.detalles_compras FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_movimientos_inventario_update BEFORE UPDATE ON public.movimientos_inventario FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();
CREATE TRIGGER trg_reportes_generados_update BEFORE UPDATE ON public.reportes_generados FOR EACH ROW EXECUTE FUNCTION public.actualizar_fecha_modificacion();

-- ============================================================
-- 13. FUNCIÓN PARA GENERAR ALERTAS DE INVENTARIO
-- ============================================================

CREATE OR REPLACE FUNCTION public.generar_alerta_stock_bajo()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.cantidad_en_stock <= NEW.stock_minimo THEN

        INSERT INTO public.alertas_inventario (
            material_id,
            tipo_alerta,
            mensaje,
            stock_actual,
            stock_minimo,
            estado,
            fecha_creacion
        )
        SELECT
            NEW.material_id,
            CASE
                WHEN NEW.cantidad_en_stock = NEW.stock_minimo THEN 'Stock Bajo'
                ELSE 'Inventario Crítico'
            END,
            'El material "' || NEW.nombre_material || '" alcanzó el inventario de seguridad. Stock actual: '
            || NEW.cantidad_en_stock || ', stock mínimo permitido: ' || NEW.stock_minimo || '.',
            NEW.cantidad_en_stock,
            NEW.stock_minimo,
            'Pendiente',
            NOW()
        WHERE NOT EXISTS (
            SELECT 1
            FROM public.alertas_inventario ai
            WHERE ai.material_id = NEW.material_id
            AND ai.estado = 'Pendiente'
        );

    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_alerta_stock_bajo
AFTER INSERT OR UPDATE OF cantidad_en_stock
ON public.materiales
FOR EACH ROW
EXECUTE FUNCTION public.generar_alerta_stock_bajo();

-- ============================================================
-- 14. FUNCIÓN: REGISTRAR ENTRADA DE MATERIAL
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_entrada_material(
    p_material_id INTEGER,
    p_cantidad INTEGER,
    p_precio_unitario NUMERIC,
    p_referencia VARCHAR,
    p_descripcion VARCHAR,
    p_usuario_id INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_nuevo INTEGER;
BEGIN
    IF p_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad de entrada debe ser mayor que cero.';
    END IF;

    SELECT cantidad_en_stock
    INTO v_stock_anterior
    FROM public.materiales
    WHERE material_id = p_material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    v_stock_nuevo := v_stock_anterior + p_cantidad;

    UPDATE public.materiales
    SET cantidad_en_stock = v_stock_nuevo
    WHERE material_id = p_material_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        p_material_id,
        'Entrada',
        p_cantidad,
        v_stock_anterior,
        v_stock_nuevo,
        p_precio_unitario,
        p_referencia,
        p_descripcion,
        p_usuario_id
    );
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 15. FUNCIÓN: REGISTRAR SALIDA DE MATERIAL
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_salida_material(
    p_material_id INTEGER,
    p_cantidad INTEGER,
    p_referencia VARCHAR,
    p_descripcion VARCHAR,
    p_usuario_id INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_nuevo INTEGER;
    v_stock_minimo INTEGER;
    v_precio_unitario NUMERIC(18,2);
BEGIN
    IF p_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad de salida debe ser mayor que cero.';
    END IF;

    SELECT cantidad_en_stock, stock_minimo, precio_unitario
    INTO v_stock_anterior, v_stock_minimo, v_precio_unitario
    FROM public.materiales
    WHERE material_id = p_material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    v_stock_nuevo := v_stock_anterior - p_cantidad;

    IF v_stock_nuevo < v_stock_minimo THEN
        RAISE EXCEPTION 'Movimiento no permitido. El inventario no puede ser menor a % unidades. Stock actual: %, salida solicitada: %, stock resultante: %.',
            v_stock_minimo, v_stock_anterior, p_cantidad, v_stock_nuevo;
    END IF;

    UPDATE public.materiales
    SET cantidad_en_stock = v_stock_nuevo
    WHERE material_id = p_material_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        p_material_id,
        'Salida',
        p_cantidad,
        v_stock_anterior,
        v_stock_nuevo,
        v_precio_unitario,
        p_referencia,
        p_descripcion,
        p_usuario_id
    );
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 16. FUNCIÓN: REGISTRAR AJUSTE DE MATERIAL
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_ajuste_material(
    p_material_id INTEGER,
    p_stock_nuevo INTEGER,
    p_referencia VARCHAR,
    p_descripcion VARCHAR,
    p_usuario_id INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_minimo INTEGER;
    v_diferencia INTEGER;
    v_precio_unitario NUMERIC(18,2);
BEGIN
    SELECT cantidad_en_stock, stock_minimo, precio_unitario
    INTO v_stock_anterior, v_stock_minimo, v_precio_unitario
    FROM public.materiales
    WHERE material_id = p_material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    IF p_stock_nuevo < v_stock_minimo THEN
        RAISE EXCEPTION 'Ajuste no permitido. El inventario no puede ser menor a % unidades.', v_stock_minimo;
    END IF;

    v_diferencia := ABS(p_stock_nuevo - v_stock_anterior);

    UPDATE public.materiales
    SET cantidad_en_stock = p_stock_nuevo
    WHERE material_id = p_material_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        p_material_id,
        'Ajuste',
        v_diferencia,
        v_stock_anterior,
        p_stock_nuevo,
        v_precio_unitario,
        p_referencia,
        p_descripcion,
        p_usuario_id
    );
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 17. FUNCIÓN PARA REGISTRAR ENTRADA DESDE DETALLES_COMPRAS
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_entrada_desde_compra()
RETURNS TRIGGER AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_nuevo INTEGER;
    v_factura VARCHAR(50);
BEGIN
    SELECT cantidad_en_stock
    INTO v_stock_anterior
    FROM public.materiales
    WHERE material_id = NEW.material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    v_stock_nuevo := v_stock_anterior + NEW.cantidad;

    UPDATE public.materiales
    SET cantidad_en_stock = v_stock_nuevo
    WHERE material_id = NEW.material_id;

    SELECT numero_factura
    INTO v_factura
    FROM public.compras
    WHERE compra_id = NEW.compra_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        NEW.material_id,
        'Entrada',
        NEW.cantidad,
        v_stock_anterior,
        v_stock_nuevo,
        NEW.precio_unitario,
        'Compra ' || COALESCE(v_factura, NEW.compra_id::TEXT),
        'Entrada automática generada desde detalle de compra.',
        NULL
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_entrada_desde_compra
AFTER INSERT ON public.detalles_compras
FOR EACH ROW
EXECUTE FUNCTION public.registrar_entrada_desde_compra();

-- ============================================================
-- 18. ALTER TABLE OWNER
-- ============================================================

ALTER TABLE public.roles OWNER TO roger;
ALTER TABLE public.empleados OWNER TO roger;
ALTER TABLE public.clientes OWNER TO roger;
ALTER TABLE public.categorias_proveedor OWNER TO roger;
ALTER TABLE public.proveedores OWNER TO roger;
ALTER TABLE public.categorias OWNER TO roger;
ALTER TABLE public.proyectos OWNER TO roger;
ALTER TABLE public.detalles_empleados OWNER TO roger;
ALTER TABLE public.materiales OWNER TO roger;
ALTER TABLE public.alertas_inventario OWNER TO roger;
ALTER TABLE public.avaluos OWNER TO roger;
ALTER TABLE public.servicios OWNER TO roger;
ALTER TABLE public.costos_directos_servicios OWNER TO roger;
ALTER TABLE public.costos_indirectos_servicios OWNER TO roger;
ALTER TABLE public.detalles_avaluos OWNER TO roger;
ALTER TABLE public.maquinarias OWNER TO roger;
ALTER TABLE public.detalles_maquinarias OWNER TO roger;
ALTER TABLE public.vehiculos OWNER TO roger;
ALTER TABLE public.detalles_vehiculos OWNER TO roger;
ALTER TABLE public.usuarios OWNER TO roger;
ALTER TABLE public.historial_alertas OWNER TO roger;
ALTER TABLE public.menu OWNER TO roger;
ALTER TABLE public.permisos OWNER TO roger;
ALTER TABLE public.compras OWNER TO roger;
ALTER TABLE public.detalles_compras OWNER TO roger;
ALTER TABLE public.movimientos_inventario OWNER TO roger;
ALTER TABLE public.reportes_generados OWNER TO roger;

-- ============================================================
-- 19. GRANT ALL
-- ============================================================

GRANT ALL ON TABLE public.roles TO roger;
GRANT ALL ON TABLE public.empleados TO roger;
GRANT ALL ON TABLE public.clientes TO roger;
GRANT ALL ON TABLE public.categorias_proveedor TO roger;
GRANT ALL ON TABLE public.proveedores TO roger;
GRANT ALL ON TABLE public.categorias TO roger;
GRANT ALL ON TABLE public.proyectos TO roger;
GRANT ALL ON TABLE public.detalles_empleados TO roger;
GRANT ALL ON TABLE public.materiales TO roger;
GRANT ALL ON TABLE public.alertas_inventario TO roger;
GRANT ALL ON TABLE public.avaluos TO roger;
GRANT ALL ON TABLE public.servicios TO roger;
GRANT ALL ON TABLE public.costos_directos_servicios TO roger;
GRANT ALL ON TABLE public.costos_indirectos_servicios TO roger;
GRANT ALL ON TABLE public.detalles_avaluos TO roger;
GRANT ALL ON TABLE public.maquinarias TO roger;
GRANT ALL ON TABLE public.detalles_maquinarias TO roger;
GRANT ALL ON TABLE public.vehiculos TO roger;
GRANT ALL ON TABLE public.detalles_vehiculos TO roger;
GRANT ALL ON TABLE public.usuarios TO roger;
GRANT ALL ON TABLE public.historial_alertas TO roger;
GRANT ALL ON TABLE public.menu TO roger;
GRANT ALL ON TABLE public.permisos TO roger;
GRANT ALL ON TABLE public.compras TO roger;
GRANT ALL ON TABLE public.detalles_compras TO roger;
GRANT ALL ON TABLE public.movimientos_inventario TO roger;
GRANT ALL ON TABLE public.reportes_generados TO roger;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO roger;

-- ============================================================
-- FIN DEL SCRIPT COMPLETO
-- ============================================================