-- ===========================================
-- DATABASE STRUCTURE FOR ACONSA
-- PostgreSQL
-- ===========================================

-- ROLES
CREATE TABLE roles (
rol_id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cargo               VARCHAR(100) NOT NULL,
descripcion         VARCHAR(150),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ
);

-- EMPLEADOS
CREATE TABLE empleados (
empleado_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombres             VARCHAR(100) NOT NULL,
apellidos           VARCHAR(100) NOT NULL,
cedula              VARCHAR(25) NOT NULL,
rol_id              INT NOT NULL,
fecha_nacimiento    DATE NOT NULL,
fecha_contratacion  DATE NOT NULL,
direccion           VARCHAR(150),
pais                VARCHAR(50),
telefono            VARCHAR(15),
correo              VARCHAR(100),
reportes            INT,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_empleados_rol
FOREIGN KEY (rol_id)
REFERENCES roles (rol_id),

CONSTRAINT fk_empleados_jefe
FOREIGN KEY (reportes)
REFERENCES empleados (empleado_id),

CONSTRAINT uq_empleados_cedula
UNIQUE (cedula),

CONSTRAINT chk_empleados_cedula
CHECK (cedula ~ '^[0-9]{13}[A-Za-z]$'),

CONSTRAINT chk_empleados_telefono
CHECK (telefono IS NULL OR telefono ~ '^[0-9]{8,15}$'),

CONSTRAINT chk_empleados_correo
CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

-- CLIENTES
CREATE TABLE clientes (
cliente_id            CHAR(5) PRIMARY KEY,
tipo_cliente          VARCHAR(30) NOT NULL,
numero_identificacion VARCHAR(50),
nombre_empresa        VARCHAR(100) NOT NULL,
nombre_contacto       VARCHAR(100),
cargo_contacto        VARCHAR(50),
direccion             VARCHAR(150),
ciudad                VARCHAR(100),
pais                  VARCHAR(50),
telefono              VARCHAR(20),
correo                VARCHAR(100),
fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion   TIMESTAMPTZ,
fecha_eliminacion     TIMESTAMPTZ,

CONSTRAINT chk_clientes_tipo_cliente
CHECK (tipo_cliente IN ('Persona Natural', 'Persona Jurídica')),

CONSTRAINT chk_clientes_identificacion
CHECK (numero_identificacion IS NULL OR numero_identificacion ~ '^[A-Za-z0-9]+$'),

CONSTRAINT chk_clientes_telefono
CHECK (telefono IS NULL OR telefono ~ '^[0-9]{8,15}$'),

CONSTRAINT chk_clientes_correo
CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

-- CATEGORÍAS DE PROVEEDOR
CREATE TABLE categorias_proveedor (
categoria_proveedor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_categoria       VARCHAR(100) NOT NULL,
descripcion            VARCHAR(150),
fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion    TIMESTAMPTZ,
fecha_eliminacion      TIMESTAMPTZ
);

-- PROVEEDORES
CREATE TABLE proveedores (
proveedor_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
categoria_proveedor_id INT NOT NULL,
nombre_empresa         VARCHAR(100) NOT NULL,
nombre_contacto        VARCHAR(100),
cargo_contacto         VARCHAR(50),
direccion              VARCHAR(150),
ciudad                 VARCHAR(100),
pais                   VARCHAR(50),
telefono               VARCHAR(15),
correo                 VARCHAR(100),
fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion    TIMESTAMPTZ,
fecha_eliminacion      TIMESTAMPTZ,

CONSTRAINT fk_proveedores_categoria
FOREIGN KEY (categoria_proveedor_id)
REFERENCES categorias_proveedor (categoria_proveedor_id),

CONSTRAINT chk_proveedores_telefono
CHECK (telefono IS NULL OR telefono ~ '^[0-9]{8,15}$'),

CONSTRAINT chk_proveedores_correo
CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

-- PROYECTOS
CREATE TABLE proyectos (
proyecto_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cliente_id          CHAR(5) NOT NULL,
nombre_proyecto     VARCHAR(100) NOT NULL,
descripcion         VARCHAR(150),
ubicacion           VARCHAR(100),
fecha_inicio        DATE NOT NULL,
fecha_fin           DATE,

tiempo_total_dias   INT GENERATED ALWAYS AS (
fecha_fin - fecha_inicio
) STORED,

presupuesto_total   NUMERIC(18,2) NOT NULL,
estado              VARCHAR(50) NOT NULL DEFAULT 'En Espera',
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_proyectos_cliente
FOREIGN KEY (cliente_id)
REFERENCES clientes (cliente_id),

CONSTRAINT chk_proyectos_presupuesto
CHECK (presupuesto_total > 0),

CONSTRAINT chk_proyectos_estado
CHECK (estado IN ('En Espera','Activo','Completado','Cancelado')),

CONSTRAINT chk_proyectos_fechas
CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

-- DETALLES EMPLEADOS
CREATE TABLE detalles_empleados (
detalle_empleado_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
empleado_id          INT NOT NULL,
proyecto_id          INT NOT NULL,
fecha_de_proyecto    DATE DEFAULT CURRENT_DATE,
fecha_creacion       TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion  TIMESTAMPTZ,
fecha_eliminacion    TIMESTAMPTZ,

CONSTRAINT fk_detalle_empleado
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT fk_detalle_proyecto
FOREIGN KEY (proyecto_id)
REFERENCES proyectos (proyecto_id),

CONSTRAINT uq_detalles_empleados_empleado_proyecto
UNIQUE (empleado_id, proyecto_id)
);

-- CATEGORÍAS
CREATE TABLE categorias (
categoria_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_categoria    VARCHAR(100) NOT NULL,
descripcion         VARCHAR(150) NOT NULL,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ
);

-- MATERIALES
CREATE TABLE materiales (
material_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_material     VARCHAR(100) NOT NULL,
categoria_id        INT,
descripcion         VARCHAR(150),
unidad_de_medida    VARCHAR(100) NOT NULL,
cantidad_en_stock   INT NOT NULL,
stock_minimo        INT NOT NULL DEFAULT 10,
precio_unitario     NUMERIC(18,2) NOT NULL,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_materiales_categoria
FOREIGN KEY (categoria_id)
REFERENCES categorias (categoria_id),

CONSTRAINT chk_materiales_stock
CHECK (cantidad_en_stock >= stock_minimo),

CONSTRAINT chk_materiales_stock_minimo
CHECK (stock_minimo >= 10),

CONSTRAINT chk_materiales_precio
CHECK (precio_unitario > 0)
);

-- ALERTAS INVENTARIO
CREATE TABLE alertas_inventario (
alerta_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
material_id         INT NOT NULL,
tipo_alerta         VARCHAR(50) NOT NULL,
mensaje             VARCHAR(250) NOT NULL,
stock_actual        INT NOT NULL,
stock_minimo        INT NOT NULL DEFAULT 10,
estado              VARCHAR(30) DEFAULT 'Pendiente',
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_atendida      TIMESTAMPTZ,
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_alertas_materiales
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT chk_alertas_tipo
CHECK (tipo_alerta IN ('Stock Bajo', 'Inventario Crítico')),

CONSTRAINT chk_alertas_estado
CHECK (estado IN ('Pendiente', 'Atendida', 'Cancelada'))
);

-- AVALUOS
CREATE TABLE avaluos (
avaluo_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proyecto_id         INT NOT NULL,
descripcion         VARCHAR(200),
monto_ejecutado     NUMERIC(18,2) NOT NULL,

fecha_inicio        TIMESTAMP NOT NULL,
fecha_fin           TIMESTAMP NOT NULL,

tiempo_total_dias   INT GENERATED ALWAYS AS (
fecha_fin::date - fecha_inicio::date
) STORED,

fecha_creacion      TIMESTAMP DEFAULT NOW(),
fecha_actualizacion TIMESTAMP,
fecha_eliminacion   TIMESTAMP,

CONSTRAINT fk_avaluos_proyecto
FOREIGN KEY (proyecto_id)
REFERENCES proyectos(proyecto_id),

CONSTRAINT chk_avaluos_monto
CHECK (monto_ejecutado >= 0),

CONSTRAINT chk_avaluos_fechas
CHECK (fecha_fin >= fecha_inicio)
);

-- SERVICIOS
CREATE TABLE servicios (
servicio_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_servicio        VARCHAR(100) NOT NULL,
descripcion            VARCHAR(200),
total_costo_directo    DECIMAL(18,2) NOT NULL,
total_costo_indirecto  DECIMAL(18,2) NOT NULL,

costo_venta            DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo + total_costo_indirecto
) STORED,

fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion    TIMESTAMPTZ,
fecha_eliminacion      TIMESTAMPTZ,

CONSTRAINT chk_servicios_total_costo_directo
CHECK (total_costo_directo > 0),

CONSTRAINT chk_servicios_total_costo_indirecto
CHECK (total_costo_indirecto > 0)
);

-- COSTOS DIRECTOS SERVICIOS
CREATE TABLE costos_directos_servicios (
costo_directo_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
servicio_id        INT NOT NULL,
material_id        INT NOT NULL,
cantidad_material  INT NOT NULL,
unidad_de_medida   VARCHAR(50) NOT NULL,
precio_unitario    NUMERIC(18,2) NOT NULL,

costo_material NUMERIC(18,2)
GENERATED ALWAYS AS (
precio_unitario * cantidad_material
) STORED,

mano_obra NUMERIC(18,2)
GENERATED ALWAYS AS (
(precio_unitario * cantidad_material) * 0.40
) STORED,

equipos_transporte_herramientas NUMERIC(18,2)
GENERATED ALWAYS AS (
(precio_unitario * cantidad_material) * 0.10
) STORED,

total_costo_directo NUMERIC(18,2)
GENERATED ALWAYS AS (
(precio_unitario * cantidad_material) +
((precio_unitario * cantidad_material) * 0.40) +
((precio_unitario * cantidad_material) * 0.10)
) STORED,

fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_cds_servicio
FOREIGN KEY (servicio_id)
REFERENCES servicios (servicio_id),

CONSTRAINT fk_cds_material
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT chk_cds_cantidad
CHECK (cantidad_material > 0),

CONSTRAINT chk_cds_precio
CHECK (precio_unitario > 0)
);

-- COSTOS INDIRECTOS SERVICIOS
CREATE TABLE costos_indirectos_servicios (
costo_indirecto_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
servicio_id            INT NOT NULL,
costo_directo_id       INT NOT NULL,
total_costo_directo    DECIMAL(18,2) NOT NULL,

administracion         DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo * 0.05
) STORED,

operacion              DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo * 0.10
) STORED,

utilidad               DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo * 0.15
) STORED,

precio_unitario        DECIMAL(18,2)
GENERATED ALWAYS AS (
(total_costo_directo * 0.05) +
(total_costo_directo * 0.10) +
(total_costo_directo * 0.15)
) STORED,

total_costo_indirecto  DECIMAL(18,2)
GENERATED ALWAYS AS (
(total_costo_directo * 0.05) +
(total_costo_directo * 0.10) +
(total_costo_directo * 0.15)
) STORED,

fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_cis_servicio
FOREIGN KEY (servicio_id)
REFERENCES servicios(servicio_id),

CONSTRAINT fk_cis_costo_directo
FOREIGN KEY (costo_directo_id)
REFERENCES costos_directos_servicios(costo_directo_id),

CONSTRAINT chk_cis_total_directo
CHECK (total_costo_directo > 0)
);

-- MAQUINARIAS
CREATE TABLE maquinarias (
maquinaria_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proveedor_id        INT,
nombre_maquinaria   VARCHAR(100) NOT NULL,
marca               VARCHAR(50),
modelo              VARCHAR(50),
precio_por_hora     NUMERIC(18,2) NOT NULL,
descripcion         VARCHAR(200),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_maquinarias_proveedor
FOREIGN KEY (proveedor_id)
REFERENCES proveedores (proveedor_id),

CONSTRAINT chk_maquinarias_precio
CHECK (precio_por_hora >= 0)
);

-- DETALLES MAQUINARIAS
CREATE TABLE detalles_maquinarias (
detalle_maquinaria_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proyecto_id           INT,
maquinaria_id         INT,
horas_utilizadas      INT,
fecha_inicio_renta    DATE NOT NULL,
fecha_fin_renta       DATE,
estado                VARCHAR(30),
fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion   TIMESTAMPTZ,
fecha_eliminacion     TIMESTAMPTZ,

CONSTRAINT fk_detalle_proyecto_maq
FOREIGN KEY (proyecto_id)
REFERENCES proyectos (proyecto_id),

CONSTRAINT fk_detalle_maquinaria
FOREIGN KEY (maquinaria_id)
REFERENCES maquinarias (maquinaria_id),

CONSTRAINT chk_detalles_maquinarias_estado
CHECK (estado IS NULL OR estado IN ('Activa','Finalizada','Cancelada')),

CONSTRAINT chk_detalles_maquinarias_horas
CHECK (horas_utilizadas IS NULL OR horas_utilizadas >= 0),

CONSTRAINT chk_detalles_maquinarias_fechas
CHECK (fecha_fin_renta IS NULL OR fecha_fin_renta >= fecha_inicio_renta)
);

-- VEHÍCULOS
CREATE TABLE vehiculos (
vehiculo_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proveedor_id        INT,
marca               VARCHAR(50) NOT NULL,
modelo              VARCHAR(50) NOT NULL,
anio                INT,
placa               VARCHAR(15) UNIQUE NOT NULL,
tipo_de_vehiculo    VARCHAR(30),
tipo_de_combustible VARCHAR(40),
estado              VARCHAR(20),
fecha_registro      DATE,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_vehiculos_proveedor
FOREIGN KEY (proveedor_id)
REFERENCES proveedores (proveedor_id),

CONSTRAINT chk_vehiculos_anio
CHECK (anio IS NULL OR anio >= 1886),

CONSTRAINT chk_vehiculos_estado
CHECK (estado IS NULL OR estado IN ('Disponible','En Mantenimiento','No Disponible')),

CONSTRAINT chk_vehiculos_combustible
CHECK (
tipo_de_combustible IS NULL
OR tipo_de_combustible IN ('Diésel', 'Regular', 'Gasolina Super')
)
);

-- DETALLES VEHÍCULOS
CREATE TABLE detalles_vehiculos (
detalle_vehiculo_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
empleado_id          INT NOT NULL,
vehiculo_id          INT NOT NULL,
fecha_asignacion     DATE NOT NULL,
fecha_fin_asignacion DATE,
descripcion          VARCHAR(100),
fecha_creacion       TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion  TIMESTAMPTZ,
fecha_eliminacion    TIMESTAMPTZ,

CONSTRAINT fk_detalle_empleado_veh
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT fk_detalle_vehiculo
FOREIGN KEY (vehiculo_id)
REFERENCES vehiculos (vehiculo_id),

CONSTRAINT chk_detalles_vehiculos_fechas
CHECK (fecha_fin_asignacion IS NULL OR fecha_fin_asignacion >= fecha_asignacion)
);

-- USUARIOS
CREATE TABLE usuarios (
usuario_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
empleado_id         INT NOT NULL,
usuario             VARCHAR(100) NOT NULL,
contrasena          VARCHAR(200) NOT NULL,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_usuarios_empleado
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT uq_usuarios_usuario
UNIQUE (usuario)
);

-- HISTORIAL ALERTAS
CREATE TABLE historial_alertas (
alerta_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usuario_id          INT,
tipo                VARCHAR(60) NOT NULL,
titulo              VARCHAR(150) NOT NULL,
mensaje             VARCHAR(300) NOT NULL,
modulo              VARCHAR(100) NOT NULL,
referencia_id       INT,
prioridad           VARCHAR(30) NOT NULL DEFAULT 'Media',
leida               BOOLEAN NOT NULL DEFAULT FALSE,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_historial_alertas_usuario
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id),

CONSTRAINT chk_historial_alertas_prioridad
CHECK (prioridad IN ('Baja', 'Media', 'Alta'))
);

-- COMPRAS
CREATE TABLE compras (
compra_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proveedor_id        INT NOT NULL,
empleado_id         INT,
numero_factura      VARCHAR(50) NOT NULL,
fecha_compra        DATE NOT NULL DEFAULT CURRENT_DATE,
monto_total         NUMERIC(18,2) NOT NULL DEFAULT 0,
estado              VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
observaciones       VARCHAR(200),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_compras_proveedor
FOREIGN KEY (proveedor_id)
REFERENCES proveedores (proveedor_id),

CONSTRAINT fk_compras_empleado
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT uq_compras_numero_factura
UNIQUE (numero_factura),

CONSTRAINT chk_compras_monto
CHECK (monto_total >= 0),

CONSTRAINT chk_compras_estado
CHECK (estado IN ('Pendiente','Pagada','Cancelada'))
);

-- DETALLES COMPRAS
CREATE TABLE detalles_compras (
detalle_compra_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
compra_id           INT NOT NULL,
material_id         INT NOT NULL,
cantidad            INT NOT NULL,
precio_unitario     NUMERIC(18,2) NOT NULL,

subtotal NUMERIC(18,2)
GENERATED ALWAYS AS (
cantidad * precio_unitario
) STORED,

fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_detalle_compra
FOREIGN KEY (compra_id)
REFERENCES compras (compra_id),

CONSTRAINT fk_detalle_materiales_comp
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT chk_detalles_compras_cantidad
CHECK (cantidad > 0),

CONSTRAINT chk_detalles_compras_precio
CHECK (precio_unitario > 0)
);

-- DETALLES AVALUOS
CREATE TABLE detalles_avaluos (
detalle_avaluo_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
avaluo_id             INT NOT NULL,
servicio_id           INT NOT NULL,
actividad             VARCHAR(100) NOT NULL,
unidad_de_medida      VARCHAR(50) NOT NULL,
cantidad              INT NOT NULL,
precio_unitario       NUMERIC(18,2) NOT NULL,

costo_venta NUMERIC(18,2)
GENERATED ALWAYS AS (
cantidad * precio_unitario
) STORED,

iva NUMERIC(18,2)
GENERATED ALWAYS AS (
(cantidad * precio_unitario) * 0.15
) STORED,

total_costo_venta NUMERIC(18,2)
GENERATED ALWAYS AS (
(cantidad * precio_unitario) +
((cantidad * precio_unitario) * 0.15)
) STORED,

observaciones         VARCHAR(200),
fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion   TIMESTAMPTZ,
fecha_eliminacion     TIMESTAMPTZ,

CONSTRAINT fk_as_avaluo
FOREIGN KEY (avaluo_id)
REFERENCES avaluos (avaluo_id),

CONSTRAINT fk_as_servicio
FOREIGN KEY (servicio_id)
REFERENCES servicios (servicio_id),

CONSTRAINT chk_detalles_avaluos_cantidad
CHECK (cantidad > 0),

CONSTRAINT chk_detalles_avaluos_precio
CHECK (precio_unitario >= 0)
);

-- MENU
CREATE TABLE menu (
id_menu        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre         VARCHAR(100) NOT NULL,
es_submenu     BOOLEAN DEFAULT FALSE,
url            VARCHAR(150),
id_menu_parent INT,
estado         BOOLEAN DEFAULT TRUE,
show           BOOLEAN DEFAULT TRUE,

CONSTRAINT fk_menu_parent
FOREIGN KEY (id_menu_parent)
REFERENCES menu (id_menu)
ON DELETE SET NULL
);

-- PERMISOS
CREATE TABLE permisos (
permiso_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usuario_id          INT NOT NULL,
id_menu             INT NOT NULL,
estado              BOOLEAN DEFAULT TRUE,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_perm_usuario
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id)
ON DELETE CASCADE,

CONSTRAINT fk_perm_menu
FOREIGN KEY (id_menu)
REFERENCES menu (id_menu)
ON DELETE CASCADE,

CONSTRAINT permisos_unique
UNIQUE (usuario_id, id_menu)
);

-- MOVIMIENTOS INVENTARIO
CREATE TABLE movimientos_inventario (
movimiento_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
material_id          INT NOT NULL,
tipo_movimiento      VARCHAR(30) NOT NULL,
cantidad             INT NOT NULL,
stock_anterior       INT NOT NULL,
stock_nuevo          INT NOT NULL,
precio_unitario      NUMERIC(18,2),

costo_total          NUMERIC(18,2)
GENERATED ALWAYS AS (
cantidad * precio_unitario
) STORED,

referencia           VARCHAR(100),
descripcion          VARCHAR(250),
usuario_id           INT,
fecha_movimiento     TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion  TIMESTAMPTZ,
fecha_eliminacion    TIMESTAMPTZ,

CONSTRAINT fk_movimientos_materiales
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT fk_movimientos_usuarios
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id),

CONSTRAINT chk_movimientos_tipo
CHECK (tipo_movimiento IN ('Entrada', 'Salida', 'Ajuste')),

CONSTRAINT chk_movimientos_cantidad
CHECK (cantidad > 0),

CONSTRAINT chk_movimientos_stock_nuevo
CHECK (stock_nuevo >= 0)
);

-- REPORTES GENERADOS
CREATE TABLE reportes_generados (
reporte_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usuario_id          INT NOT NULL,
nombre_reporte      VARCHAR(150) NOT NULL,
tipo_reporte        VARCHAR(20) NOT NULL,
descripcion         VARCHAR(200),
datos               JSONB,
archivo_url         VARCHAR(255) NOT NULL,
ip_generacion       VARCHAR(50),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_reporte_usuario
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id),

CONSTRAINT chk_reportes_tipo
CHECK (tipo_reporte IN ('PDF','EXCEL'))
);
